-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "DP-1",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local vars = require("vars")

--$runmenu = wofi --show run

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- Hyprland tools exec

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox

-- Polkit

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 6,
		border_size = 1,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		col = {
			active_border = { colors = { "rgba(aa33ffee)", "rgba(11aabbee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 10,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.85,
		shadow = {
			enabled = true,
			range = 20,
			render_power = 2,
			offset = { 0, 8 },
			color = "rgba(04030270)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 9,
			passes = 2,
			vibrancy = 0.3,
		},
	},
})

-- Animations
hl.config({
	animations = {
		enabled = true,
		-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "default", style = "popin" })

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "se,us",
		kb_variant = "",
		kb_model = "",
		kb_options = "grp:win_space_toggle",
		kb_rules = "",
		follow_mouse = 1,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		accel_profile = "flat",
		touchpad = {
			natural_scroll = true,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
	gestures = {},
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

--###################
--## KEYBINDINGSS ###
--###################
-- Here the keybinds are setup
-- See https://wiki.hyprland.org/Configuring/Keywords/
require("keybinds.standard")(vars)

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

hl.window_rule({
	name = "apply_to_webbrowsers",
	match = {
		class = "(firefox|[C|c]hromium)",
	},
	workspace = 2,
	opacity = "1.0 override 1.0 override",
})

hl.window_rule({
	name = "suppress_maximize",
	match = {
		class = "*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name = "move_chat_to_4",
	match = {
		class = "discord",
	},
	workspace = 4,
})

hl.window_rule({
	name = "move_keepass_to_6",
	match = {
		class = "^(org\\.keepassxc\\.KeePassXC)$",
	},
	workspace = 6,
})

--##############################
--# Game specific window rules #
--##############################
-- Genshin impact
hl.window_rule({
	name = "genshin-multi-monitor-lock",
	match = {
		class = "steam_proton",
		title = "Genshin Impact",
	},
	allows_input = true,
	immediate = true,
	confine_pointer = true, -- <--- Hard-blocks mouse from leaving onto adjacent screens
})

-- Workspace rules

hl.workspace_rule({
	workspace = 1,
	default_name = "1:",
})

hl.workspace_rule({
	workspace = 2,
	default_name = "2:",
})

hl.workspace_rule({
	workspace = 3,
	default_name = "3:",
})

hl.workspace_rule({
	workspace = 4,
	default_name = "4:",
})

hl.workspace_rule({
	workspace = 5,
	default_name = "5:",
})

hl.workspace_rule({
	workspace = 6,
	default_name = "6:",
})

hl.workspace_rule({
	workspace = 7,
	default_name = "7:",
})

hl.workspace_rule({
	workspace = 8,
	default_name = "8:",
})

hl.workspace_rule({
	workspace = 9,
	default_name = "9:",
})

hl.workspace_rule({
	workspace = 10,
	default_name = "10:",
})

-- Set the wallpaper (starts hyprpaper first if it isn't already running).
-- config.reloaded does not fire on the initial startup, so this must also
-- run from hyprland.start to set the wallpaper at boot.
local function reload_hyprland()
	local set_wallpaper =
		[[sh -c "if [ -z $(pidof hyprpaper) ]; then hyprpaper & sleep 3s; fi; ~/.config/hypr/setwallpaper.sh"]]

	local load_hyprpm = [[hyprpm reload -n]]

	hl.exec_cmd(set_wallpaper)
	hl.exec_cmd(load_hyprpm)
end

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("~/bin/myscripts/hyprboot")

	reload_hyprland()
end)

-- Exec (re-randomize the wallpaper on every reload)
hl.on("config.reloaded", function()
	reload_hyprland()
end)
