-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "DP-1",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "ghostty --working-directory=."

local fileManager = terminal .. " -e ranger"

--$menu = wofi --show drun -I

local menu = "j4-dmenu-desktop --dmenu='bemenu -i --binding vim' --term='ghostty'"

local runmenu = "bemenu-run"

--$runmenu = wofi --show run

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- Hyprland tools exec

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox

-- Polkit

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 6,
		border_size = 1,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		col = {
			active_border = { colors = { "rgba(aa33ffee)", "rgba(11aabbee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 10,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.85,
		shadow = {
			enabled = true,
			range = 20,
			render_power = 2,
			offset = { 0, 8 },
			color = "rgba(04030270)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 9,
			passes = 2,
			vibrancy = 0.3,
		},
	},
})

-- Animations
hl.config({
	animations = {
		enabled = true,
		-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "default", style = "popin" })

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "se,us",
		kb_variant = "",
		kb_model = "",
		kb_options = "grp:win_space_toggle",
		kb_rules = "",
		follow_mouse = 1,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		accel_profile = "flat",
		touchpad = {
			natural_scroll = true,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
	gestures = {},
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

--###################

--## KEYBINDINGSS ###

--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "RETURN", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(fileManager))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "space", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd(runmenu))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move focus with mainMod + vim keys directions

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- swap windows around with arrows

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.swap({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.swap({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.swap({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.swap({ direction = "down" }))

-- swap windows around with vim keys

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.swap({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.swap({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.swap({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.swap({ direction = "down" }))

-- Resize Mode

hl.bind(mainMod .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
	-- Resize windows with arrows (relative=true => resizeactive-style relative resize)
	hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }))
	hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }))
	hl.bind("up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }))
	hl.bind("down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }))
	-- Resize windows with vim keys
	hl.bind("H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }))
	hl.bind("L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }))
	hl.bind("K", hl.dsp.window.resize({ x = 0, y = -10, relative = true }))
	hl.bind("J", hl.dsp.window.resize({ x = 0, y = 10, relative = true }))
	hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.submap("screenshot"))

hl.define_submap("screenshot", function()
	hl.bind(
		"Print",
		hl.dsp.exec_cmd(
			"sh -c grim ~/Pictures/$(date +\\\"%Y-%m-%d-%T\\\")-screenshot.png && notify-send -t 2 'screenshot taken'"
		)
	)
	hl.bind("Print", hl.dsp.submap("reset"))
	hl.bind("CONTROL" .. " + " .. "c", hl.dsp.exec_cmd("grim -g $(slurp)-| wl-copy"))
	hl.bind("CONTROL" .. " + " .. "c", hl.dsp.submap("reset"))
	hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Changing workspace
-- Also includes moving window to a certain workspace
for i = 1, 10 do
	local key = i % 10 -- making sure i = 10 maps backs to 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Move current workspace to monitor

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
hl.bind(mainMod .. " + " .. "SHIFT" .. "+" .. "N", hl.dsp.workspace.move({ monitor = "+1" }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume and brightness control

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute 0 toggle"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("sh -c pactl set-sink-mute 0 false ; pactl set-sink-volume 0 +5%"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("sh -c pactl set-sink-mute 0 false ; pactl set-sink-volume 0 -5%"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"))

-- MISC Keybinds

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.exec_cmd("loginctl lock-session"))

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

hl.window_rule({
	name = "apply_to_webbrowsers",
	match = {
		class = "(firefox|[C|c]hromium)",
	},
	workspace = 2,
	opacity = "1.0 override 1.0 override",
})

hl.window_rule({
	name = "suppress_maximize",
	match = {
		class = "*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name = "move_chat_to_4",
	match = {
		class = "discord",
	},
	workspace = 4,
})

hl.window_rule({
	name = "move_keepass_to_6",
	match = {
		class = "^(org\\.keepassxc\\.KeePassXC)$",
	},
	workspace = 6,
})

-- Workspace rules

hl.workspace_rule({
	workspace = 1,
	default_name = "1:",
})

hl.workspace_rule({
	workspace = 2,
	default_name = "2:",
})

hl.workspace_rule({
	workspace = 3,
	default_name = "3:",
})

hl.workspace_rule({
	workspace = 4,
	default_name = "4:",
})

hl.workspace_rule({
	workspace = 5,
	default_name = "5:",
})

hl.workspace_rule({
	workspace = 6,
	default_name = "6:",
})

hl.workspace_rule({
	workspace = 7,
	default_name = "7:",
})

hl.workspace_rule({
	workspace = 8,
	default_name = "8:",
})

hl.workspace_rule({
	workspace = 9,
	default_name = "9:",
})

hl.workspace_rule({
	workspace = 10,
	default_name = "10:",
})

-- Set the wallpaper

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("~/bin/myscripts/hyprboot")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
	hl.exec_cmd([[sh -c "if [ -z $(pidof hyprpaper) ]; then hyprpaper& sleep 2s; fi; ~/.config/hypr/setwallpaper.sh"]])
end)
