# Cuda stuff
export LD_LIBRARY_PATH=/opt/cuda/lib64

# IM module variables
#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
#export SDL_IM_MODULE=fcitx

# QT Look and feel
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_QPA_PLATFORMTHEME=qt5ct
