# Ranger (Can these be in it's own file?)
export RANGER_LOAD_DEFAULT_RC=FALSE

# Big ENV Variables per shell, (TODO: Move path to zshrc?)
export VISUAL=nvim
export EDITOR=$VISUAL

path+=("$HOME"'/bin')
path+=("$HOME"'/bin/myscripts')

export PATH
export PE_DIR=/home/xiaoming/Documents/ProgrammingExercises/

#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
