ZDOTDIR=$HOME/.zshrc.d/

# Source standard configurations
source $ZDOTDIR/autoload/*

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install
