#!/bin/sh
bgimage=/tmp/background.png
lockicon=~/.lock.icon.png

grim $bgimage
magick $bgimage -resize 10% $bgimage
magick $bgimage -resize 1000% $bgimage
magick $bgimage $lockicon -gravity center -compose over -composite $bgimage
swaylock -i $bgimage --indicator-radius 100 -f
