#!/bin/sh
bgimage=/tmp/background.png
lockicon=~/.lock.icon.png

grim -o DP-1 $bgimage
convert $bgimage -resize 5% $bgimage
convert $bgimage -resize 2000% $bgimage
convert $bgimage $lockicon -gravity center -compose over -composite $bgimage
swaylock -i $bgimage --indicator-radius 100 -f
