#!/bin/bash

if [[ ! $(pgrep -u $UID -x fcitx5) ]]; then
	fcitx5 -d &
	nm-applet --indicator --sm-disabled &
    udiskie &
	dropbox &
	dunst &
    gammastep-indicator &
    pasystray &
    sleep 20
    nextcloud &
fi

